### ISSUE TITLE
Object Diagram(Design)

### ISSUE THREAD

**Issue by tjswns494** [minn951120/SimpleMerge#11]
![design](https://user-images.githubusercontent.com/12164927/40161175-e694725c-59ea-11e8-8b50-5b87e7614cda.PNG)
용어나 마음에 안드시는거 있으면 말해주세요

**Comment by comnamu18** [comment]
아까 회의때도 살짝 궁금했던건데 Button이랑 TextArea가 Model_Left나 _right에 묶여 있으면 Model_Left 전체를 바인딩 하면 되지 않나요..??

**Comment by dispe1** [comment]
boolean 변수들의 이름을 isCompared, isLoadedLeft(or Right) 등으로 좀더 알아보기 쉽게 바꾸는게 좋을 것 같습니다.
