### ISSUE TITLE
Object Diagram(Design) 개정

### ISSUE THREAD

**Issue by tjswns494** [minn951120/SimpleMerge#14]
<img width="637" alt="1" src="https://user-images.githubusercontent.com/12164927/40221996-04543970-5ab9-11e8-9477-74693bf737ae.PNG">
<img width="635" alt="2" src="https://user-images.githubusercontent.com/12164927/40221998-0555179a-5ab9-11e8-8f38-60bd93aa153c.PNG">

Button이랑 TextArea가 Model_Left나 _right에 묶여 있으면 Model_Left 전체를 바인딩 하면 되지 않나요..??
이라는 질문이 있었는데 저도 살짝 의문이 들어 둘다 만들어 봤어요

**Comment by comnamu18** [comment]
오늘 회의를 통해 답을 얻으셨길 빕니다..
