### ISSUE TITLE
Coding Convention : 명명규칙

### ISSUE THREAD

**Issue by minn951120** [minn951120/SimpleMerge#20]
Camel Case에 따라서 작성해주세요.
method, variable 명칭은 소문자로 시작
class 명칭은 대문자로 시작

**Comment by comnamu18** [comment]
주석이나 명명규칙 다른 건 없나요?
bool 타입관련 메소드들은 이중부정형(isNotExisted)와 같은 형태를 사용하지 않는다던가..
없으면 이슈에 넣어서 의견받을게 아니라 리드미 같은데에 써두면 되지 않을까 생각합니다.

**Comment by minn951120** [comment]
넹 contributing.md를 만들게여
