### ISSUE TITLE
SRS V0.3 Uploaded!!

### ISSUE THREAD

**Issue by star7357** [minn951120/SimpleMerge#3]
Use case가 포함된 SRS를 업로드해 두었으니 확인해주세요. 아직 부족한 부분도 많고, 특히 빨간 글씨 부분은 역시 논의가 필요한 부분이니 주의해서 읽어주시고 월요일 회의때 더 다듬는 걸로 합시다. :)
[SETeamProject_Team7_v0.3(2018.05.10).docx](https://github.com/minn951120/SimpleMerge/files/1992730/SETeamProject_Team7_v0.3.2018.05.10.docx)

**Comment by tjswns494** [comment]
UC2 Flow of Events for the Edit  Use Case에서
2개의 text field에 대하여 각각의 Edit버튼이 존재한다. Edit버튼을 누르면, Edit 버튼이 눌린 상태로 표시되며 해당 Edit버튼이 속한 text field의 내용을 편집할 수 있다. 동시에 Compare 버튼이 활성화 되어 Compare기능을 사용할 수 있게 된다. 
=>여기서 edit 버튼이 눌려야지만 compare 버튼이 활성화 되는 건가요?만약 그렇다면 양쪽 모두의 edit 버튼이 눌려야지 compare가 활성화 되나요?

**Comment by tjswns494** [comment]
UC6 Flow of Events for the Copy All Use Case에서
precondition에 커서나 선택 영역이 음영 처리된 부분 위에 있거나 포함하지 않아야 한다.가 있는데 이런 조건은 없애도 되지 않을까요?아니면 아예 compare할때 edit 기능을 비활성화 시켜 커서나 선택 영역을 아예 없애도 될거 같아요(어차피 copy all이니까요)
E1에서 일부분만 copy되는데 그럼 copy all이 아니지 않아요? copy all은 무조건 다 옮기는게 좋을 거 같아요

**Comment by comnamu18** [comment]
UC2 Edit의 경우 조금 더 논의가 필요할 것 같습니다. Usecase들을 읽어보니 UC4의 precondition에는 load나 edit이후에는 compare가 가능하다로 되어 있는데 UC2에서만 UC4와 연결을 시켜놔서 일관성이 없는 것 같습니다.
uc6과 관련해서 동일한 의견가지고 있습니다.

**Comment by minn951120** [comment]
1. Target Platforms에서 'Windows 10 기반 운영체제'보단 'Windows7, Window10'로 하는게 좋지 않을까요. '기반 운영체제'라고 붙인 이유가 있으신가요?
2. srs버전별로 안나누고 커밋하셔도 깃에서 버전관리해주는데 버전별로 파일 따로 만드는 이유 있으신가요?

**Comment by comnamu18** [comment]
1. Target Platforms 관련해서 작성하라고 되어 있어서 일단 제 운영체제만 적었습니다. 테스팅 가능한 OS종류만 적으려고 생각해서 임시로 작성했을 뿐 큰 의미는 없습니다..
2. 깃에서 버전관리하는게 익숙치 않아서..일단 버전별로 파일만들고 있습니다.

**Comment by minn951120** [comment]
회의로 결정 완료. 클로즈합니다.
