### ISSUE TITLE
MVC에 관하여

### ISSUE THREAD

**Issue by seolking** [minn951120/SimpleMerge#4]
저희가 Controller에 관하여 이야기할 때 Controller에서 버튼의 입력을 받아서 Load, Save 등등의 동작을 수행하는 것으로 이야기하지 않았나요? 그런데 MVC 모델이 User의 입력을 Controller가 받아서 그것을 Model로 보내고, Model에서 수행한 결과를 View를 통해 보여주는 것이라고 하면.

Controller는 버튼이 눌리는 것을 확인
Model이 Load, Save 등등의 역할 수행
View는 GUI 및 Model의 수행 후의 피드백
이 되는 것이 맞지 않나요?

어제 대강 그려봤던 class diagram과는 많이 다른 것 같아서요

**Comment by minn951120** [comment]
제가 생각하는 Model은 역할(기능)을 수행하지 않습니다. 단지 그 기능에 대한 정보를 저장할 뿐이지요. 사실 어떤 부분에서 더 책임을 지느냐의 문제겠지만요..
대부분 컨트롤러가 그 책임을 지는게 맞다고 생각합니다. 굳이 모델이 책임을 분담한다면, 주어진 스트링(혹은 바이트 배열)을 받아서 그 내용으로 모델을 구성하는 생성자나 set함수 정도일까요.
다른 분들 의견도 궁금합니다.

**Comment by dispe1** [comment]
view의 버튼이 눌렸을 때 이벤트가 발생하게 되고, 버튼에 등록된 이벤트 핸들러가 이벤트를 처리하게 되는데, 이 때 Controller의 메소드(load, save 등)를 불러오게 될 겁니다. Controller의 메소드가 Model을 불러와서 정보를 저장하거나 저장된 정보를 불러와서 이를 처리하기 때문에 실제 작업은 Controller에서 이루어지게 될 거 같습니다. 실제 구현이 이런 방향으로 이루어진다면 그 때 그렸던 아래의 class diagram과 비슷하게 나올 것 같습니다. 그리고 그 날 model에서 set, get 함수만 얘기했었는데, 생성자도 만드는 편이 좋을 것 같습니다.
![kakaotalk_20180515_113633104](https://user-images.githubusercontent.com/37182746/40086918-50b84d54-58db-11e8-9ad9-acb3f9ec065c.jpg)

**Comment by comnamu18** [comment]
사진보면서 느낀건데 model이 view에도 연결되어 있어야 하는것 아닌가요?
Controller가 Model의 내용을 Set해주면 Set된 내용을 View에서 get해서 표시 하는 것 아닌가 싶네요.
![mvc-steps](https://user-images.githubusercontent.com/13430579/40152672-1ea4fb96-59c1-11e8-9e1e-fa434455cbad.PNG)
위 사진은 http://sce2.umkc.edu/BIT/burrise/pl/design-patterns/ 에서 가져온 MVC설계 예시인데 Observable 을 extend 함으로써 update를 계속해서 시킬 수 있다고 합니다.
위 링크하단에 보시면 example에 관련한 코드들도 나오니 참고 가능할 것 같습니다.
약간의 차이긴한데.. 그림이 조금 맞지 않는 것 같아서 참고할 수 있는 자료들 찾아봤습니다..
다른 예시 : https://developer.apple.com/library/content/documentation/General/Conceptual/CocoaEncyclopedia/Model-View-Controller/Model-View-Controller.html

**Comment by minn951120** [comment]
아 다르고 어 다른 이야기였습니다.
닫습니다.
추가적인 상황은 조금 더 자세하게 이슈로 올려주세요.
