### ISSUE TITLE
QA result

### ISSUE THREAD

**Issue by comnamu18** [minn951120/SimpleMerge#47]
Test file with 4
![image](https://user-images.githubusercontent.com/13430579/40886507-fab4091e-6773-11e8-828b-a7d6d5d65d07.png)
- 2/4/8 failed
Test file with 5
![image](https://user-images.githubusercontent.com/13430579/40886512-18a1f710-6774-11e8-87fa-b4de862740cd.png)
- duplicate checking failed
Test file with 8
![image](https://user-images.githubusercontent.com/13430579/40886523-7e51b726-6774-11e8-9e20-7569ee1c83ad.png)
- fucntion max line ~ var 선언부 failed
Test file with 9
![image](https://user-images.githubusercontent.com/13430579/40886531-aec2d3f4-6774-11e8-82f2-486932b2d21e.png)
- AA 우측과 좌측 매칭 failed
Test file with 13
![image](https://user-images.githubusercontent.com/13430579/40886546-fbee59fa-6774-11e8-84c2-8ec0bbf83634.png)
- Mapping 실패

LCS 문제라고 여겨집니다. 추가로 LOAD시 background clear 해주시길 바랍니다..

**Comment by minn951120** [comment]
좋네요. 백그라운드 클리어는 완료했습니다.

**Comment by seolking** [comment]
Close please
