### ISSUE TITLE
isCompare toggle관련

### ISSUE THREAD

**Issue by star7357** [minn951120/SimpleMerge#79]
boolean isCompared는 compare버튼이 눌려 양쪽 subModel의 textPage에서 비교를 했는지 안했는지 나타내는 변수로, 변경사항에 대해 양쪽 textPage내용을 비교 했다면 true, 비교하지 않았다면 false를 내뱉는 변수입니다. 이는 후에 copy기능을 위해서 필요한데, 현재 textPage내용이 compare이 정상적으로 작동하여 isCompared가 true로 셋된 이후에, load나 edit을 통해 내용이 수정되어도 isCompared는 바뀌지 않습니다.  이런 경우 compare이 진행되지 않았는데도 불구하고 copy가 가능한 상태라는 말이 됩니다. 수정해야할 것 같아요 :)

**Comment by seolking** [comment]
전에 이거에 관해서 이야기를 했을 때, 한번의 copy(left to right이던 right to left이던)를 수행한 후에 다른 라인에 대해서 copy를 바로 수행할 수도 있기 때문에 compare가 한번 눌리고 나서는 isCompared가 true로 고정하기로 한 걸로 알고 있습니다

**Comment by star7357** [comment]
아아 그러면 맞게 동작하는 거였군요. 멋지다. 해당 이슈는 닫아도 될거 같아서 close하도록 하겠습니다.
