### ISSUE TITLE
구현 시 기능을 크게 두 분류로 나누는 것에 대해

### ISSUE THREAD

**Issue by minn951120** [minn951120/SimpleMerge#8]
하나의 TextField에서만 작용하는 기능 (edit, save, load),
두 TextField 모두에 작용하는 기능 (compare, copy)

이 두 분류로 나누어 구현하는 것이 좋을 것 같은데 다른 분들 의견은 어떤 지 궁금합니다.
컨트롤러 클래스를 하나만 두자니 너무 크기가 커질 것 같아 물어봅니다.

**Comment by dispe1** [comment]
프로그램이 실행되는 동안 왼쪽 텍스트와 오른쪽 텍스트에 해당하는 모델의 객체를 어디에서 생성해서 유지하는 지에 따라 정해질 것 같습니다. 컨트롤러 클래스 안에서 한다면 하나로 구현하는 것이 맞을 것이고, 모델 객체 생성을 다른 곳에서 하고 컨트롤러 클래스의 메소드를 부를 때 매개변수로 모델의 객체를 넘겨준다면 컨트롤러 클래스를 나눠도 문제는 없을 것 같습니다. 
물론 구현 상의 어려움이 있다면 클래스를 나눠야겠지만 그런 것이 아니라면 하나의 컨트롤러 클래스에 구현하는 것이 구조적으로 더 좋지 않을까요?

**Comment by minn951120** [comment]
결국 나누기로
